# Generated by Django 5.0 on 2024-09-04 10:31

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('entitle', models.CharField(max_length=200, verbose_name='عنوان انگلیسی')),
                ('description', tinymce.models.HTMLField(verbose_name='توضیحات')),
                ('endescription', tinymce.models.HTMLField(verbose_name='توضیحات انگلیسی')),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('entitle', models.CharField(max_length=200, verbose_name='عنوان انگلیسی')),
                ('phone_number', models.CharField(max_length=200, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('enaddress', models.TextField(verbose_name='آدرس انگلایسی')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='FirstTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('entitle', models.CharField(max_length=200, verbose_name='عنوان انگلیسی')),
                ('description', tinymce.models.HTMLField(verbose_name='توضیحات')),
                ('endescription', tinymce.models.HTMLField(verbose_name='توضیحات انگلیسی')),
                ('image', models.ImageField(upload_to='first_title/', verbose_name='تصویر')),
                ('location', models.TextField(verbose_name='موقعیت مکانی')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('entitle', models.CharField(max_length=200, verbose_name='عنوان انگلیسی')),
                ('image1', models.ImageField(upload_to='services/', verbose_name='تصویر1 از سمت چپ')),
                ('description1', models.CharField(max_length=200, verbose_name='توضیحات عکس ۱')),
                ('endescription1', models.CharField(max_length=200, verbose_name='توضیحات عکس ۱ انگلیسی')),
                ('image2', models.ImageField(upload_to='services/', verbose_name='تصویر2 از سمت چپ')),
                ('description2', models.CharField(max_length=200, verbose_name='توضیحات عکس 2')),
                ('endescription2', models.CharField(max_length=200, verbose_name='توضیحات عکس 2 انگلیسی')),
                ('image3', models.ImageField(upload_to='services/', verbose_name='تصویر3 از سمت چپ')),
                ('description3', models.CharField(max_length=200, verbose_name='توضیحات عکس 3')),
                ('endescription3', models.CharField(max_length=200, verbose_name='توضیحات عکس 3 انگلیسی')),
                ('image4', models.ImageField(upload_to='services/', verbose_name='تصویر4 از سمت چپ')),
                ('description4', models.CharField(max_length=200, verbose_name='توضیحات عکس 4')),
                ('endescription4', models.CharField(max_length=200, verbose_name='توضیحات عکس 4 انگلیسی')),
                ('image5', models.ImageField(upload_to='services/', verbose_name='تصویر5 از سمت چپ')),
                ('description5', models.CharField(max_length=200, verbose_name='توضیحات عکس 5')),
                ('endescription5', models.CharField(max_length=200, verbose_name='توضیحات عکس 5 انگلیسی')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
