# Generated by Django 5.0 on 2024-09-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image1',
            field=models.TextField(verbose_name='تصویر1 از سمت چپ'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image2',
            field=models.TextField(verbose_name='تصویر2 از سمت چپ'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image3',
            field=models.TextField(verbose_name='تصویر3 از سمت چپ'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image4',
            field=models.TextField(verbose_name='تصویر4 از سمت چپ'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image5',
            field=models.TextField(verbose_name='تصویر5 از سمت چپ'),
        ),
    ]
