# Generated by Django 5.0 on 2024-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_firsttitle_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='en_address',
            new_name='en_description',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='fa_address',
            new_name='fa_description',
        ),
        migrations.AlterField(
            model_name='firsttitle',
            name='image',
            field=models.ImageField(upload_to='first_title/', verbose_name='تصویر 1'),
        ),
        migrations.AlterField(
            model_name='firsttitle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='first_title/', verbose_name='تصویر 2 آپشنال'),
        ),
    ]
