# Generated by Django 5.0 on 2024-09-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_en_address_contactus_en_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firsttitle',
            name='location',
        ),
        migrations.AddField(
            model_name='contactus',
            name='location',
            field=models.TextField(default='به زودی', verbose_name='موقعیت مکانی'),
        ),
    ]
