# Generated by Django 5.0 on 2024-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_firsttitle_location_contactus_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='location',
            field=models.TextField(verbose_name='موقعیت مکانی'),
        ),
    ]
