# Generated by Django 5.0 on 2024-09-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_updating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updating',
            options={'verbose_name': 'وضعیت توسعه', 'verbose_name_plural': 'وضعیت توسعه'},
        ),
        migrations.AlterField(
            model_name='updating',
            name='status',
            field=models.BooleanField(default=False, verbose_name='فعال کردن وضعیت توسعه'),
        ),
    ]
