# Generated by Django 4.2 on 2024-10-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_updating_options_alter_updating_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='en_description',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='en_description',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='firsttitle',
            name='en_description',
        ),
        migrations.RemoveField(
            model_name='firsttitle',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='en_description1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='en_description2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='en_description3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='en_description4',
        ),
        migrations.RemoveField(
            model_name='services',
            name='en_description5',
        ),
        migrations.RemoveField(
            model_name='services',
            name='en_title',
        ),
    ]
