# Generated by Django 4.2 on 2024-10-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_aboutus_en_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
