# Generated by Django 4.2 on 2024-10-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_indexswiper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexswiper',
            options={'verbose_name': 'اسلاید صفحه اول', 'verbose_name_plural': 'اسلاید صفحه اول'},
        ),
    ]
