# Generated by Django 4.2 on 2024-10-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_indexswiper_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='لوگو'),
        ),
    ]
