# Generated by Django 5.0 on 2024-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='star',
            field=models.BooleanField(default=False, verbose_name='دسته بندی ستاره دار'),
        ),
    ]
