# Generated by Django 5.0 on 2024-09-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='en_description',
            new_name='endescription',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='en_name',
            new_name='enname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='en_description',
            new_name='endescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='en_name',
            new_name='enname',
        ),
    ]
