# Generated by Django 5.0 on 2024-09-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_en_description_category_endescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='endescription',
            new_name='en_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='enname',
            new_name='en_title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='fa_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='fa_title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='endescription',
            new_name='en_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='enname',
            new_name='en_title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='fa_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='fa_title',
        ),
    ]
