# Generated by Django 5.0 on 2024-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='photo', upload_to='category/', verbose_name='عکس'),
        ),
    ]
