# Generated by Django 4.2 on 2024-10-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='en_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='en_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='en_title',
        ),
    ]
