# Generated by Django 4.2 on 2024-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_en_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fa_description_short',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='fa_description_short',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
